backend:
  name: github
  repo: Kanta02cer/JAA.HP
  branch: main
  auth_endpoint: https://api.netlify.com/auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "ニュース記事"
    folder: "_news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "レイアウト", name: "layout", widget: "hidden", default: "news-detail"}
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "説明", name: "description", widget: "text"}
      - {label: "日付", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "カテゴリ", name: "category", widget: "select", options: ["プレスリリース", "メディア掲載", "イベント", "お知らせ"]}
      - {label: "タグ", name: "tags", widget: "list", default: []}
      - {label: "画像", name: "image", widget: "image", required: false}
      - {label: "内容", name: "body", widget: "markdown"}
      - {label: "SEO用キーワード", name: "keywords", widget: "string", required: false}
      - {label: "著者", name: "author", widget: "string", default: "日本学生アンバサダー協会"}
      - {label: "公開状態", name: "draft", widget: "boolean", default: false}

  - name: "pages"
    label: "ページ"
    files:
      - file: "index.html"
        label: "トップページ"
        name: "index"
        fields:
          - {label: "ヒーローセクション タイトル", name: "hero_title", widget: "string"}
          - {label: "ヒーローセクション サブタイトル", name: "hero_subtitle", widget: "string"}
          - {label: "ミッション タイトル", name: "mission_title", widget: "string"}
          - {label: "ミッション 説明", name: "mission_description", widget: "text"}
          - {label: "表示するニュース数", name: "news_count", widget: "number", default: 3}

local_backend: false
